# Site settings
name: 张雪
location: 北京
company: 有利网
position: 高级Java开发工程师
github: https://github.com/zhangxue1989
facebook: https://www.facebook.com/
phone: 150305xxxxx
email: xxxx@xxx.com

baseurl: ""

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

