# Site settings
name: 张雪
sex: 男
birth: 1989-06-28
location: 北京
company: 有利网
position: 高级Java开发工程师
github: https://github.com/zhangxue1989
facebook: https://www.facebook.com/
phone: 150305xxxxx
education: 本科
email: xxxx@xxx.com
#english: CET-6
#Japanese: 一级
skills: [
  {name : "aaa", level: 1 },
  {name : "bbb", level: 2 },
  {name : "ccc", level: 3 },
  {name : "ddd", level: 4 }
]



baseurl: ""

home.url : http://zx19890628.gitee.io/

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

