# Site settings
name: 张雪
sex: 男
birth: 1989-06-28
location: 北京
company: 有利网
position: 高级Java开发工程师
github: https://github.com/zhangxue1989
gitee: https://gitee.com/zx19890628
facebook: https://www.facebook.com/
phone: 15030518550
education: 本科
email: 15030518550@163.com
#english: CET-6
#Japanese: 一级
# 技能，满级为10，最低为1
skills: [
  {name : "Java", level: 8 },
  {name : "Python", level: 7 },
  {name : "Hibernate", level: 7 },
  {name : "MyBatis", level: 7 },
  {name : "Spring MVC", level: 7 },
  {name : "Spring Boot", level: 7 },
  {name : "Spring Cloud", level: 6 },
  {name : "MyBatis", level: 7 },
  {name : "MySQL", level: 8 },
  {name : "Oracle 11g", level: 6 },
  {name : "Tomcat", level: 8 },
  {name : "Nginx", level: 7 },
  {name : "Redis", level: 8 },
  {name : "Hadoop", level: 6 },
  {name : "hbase", level: 6 },
  {name : "WebGIS", level: 6 },
  {name : "HighCharts", level: 6 },
  {name : "Bootstarp3", level: 6 }
]



baseurl: ""

homeUrl: http://www.zx1989.top

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

